networks:
  playground:
    external: false

services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - playground

  playground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground
    environment:
      - VIRTUAL_HOST=playground.localhost
    depends_on:
      - redis
      - postgres
      - reverse-proxy
    volumes:
      - ../app:/var/www
    env_file:
      - .env
    expose:
      - "80"
    ports:
      - "8080:80"
      - "9003:9003"
    networks:
      - playground

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - playground
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playground_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - playground

volumes:
  postgres_data:
