networks:
  playground:
    external: false

services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - playground

  playground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground
    environment:
      - VIRTUAL_HOST=playground.localhost
    depends_on:
      - redis
      - reverse-proxy
    volumes:
      - ../app:/var/www
    env_file:
      - .env
    expose:
      - "80"
    ports:
      - "8080:80"
      - "9003:9003"
    networks:
      - playground

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - playground
    ports:
      - "6379:6379"
