imports:
    - { resource: services/commands.yaml }
    - { resource: services/controllers.yaml }
    - { resource: services/http_client.yaml }
    - { resource: services/persistence.yaml }
    - { resource: services/redis.yaml }
    - { resource: services/services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
