imports:
    - { resource: services/controllers.yaml }
    - { resource: services/persistence.yaml }
    - { resource: services/redis.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
