services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Adapter\Framework\Http\Controller\:
        resource: '%kernel.project_dir%/src/Adapter/Framework/Http/Controller/*'
        tags: [ 'controller.service_arguments' ]
