services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Adapter\Framework\Http\:
        resource: '%kernel.project_dir%/src/Adapter/Framework/Http/*'

    App\Application\Service\:
        resource: '%kernel.project_dir%/src/Application/Service/*'
